#! /bin/sh
# Noteditor - Emacs Editor based on FG42
#
# Copyright (c) 2023 Behnam Khanbeigi <yottanami@gnu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

eval `ssh-agent -s`

#export NOTEDITOR_HOME=$(cd "$(dirname "$0")/." >/dev/null 2>&1 ; pwd -P)
#export NOTEDITOR_HOME=/home/yottanami/src/personal/noteditor
export NOTEDITOR_HOME=$(cd "$(dirname "$0")/." >/dev/null 2>&1 ; pwd -P)
SHELL=/bin/sh LIBRARY_PATH=$(cc -print-file-name=libgccjit.so):$LIBRARY_PATH ${EMACS_PATH:-emacs} --name Noteditor --no-site-file --no-site-lisp --no-splash --title Noteditor --eval "(setq noteditor-mode 'editor)" -l /home/yottanami/src/personal/noteditor/noteditor-config.el "$@"
