#! /bin/sh
# Noteditor - Emacs Editor based on FG42
#
# Copyright (c) 2023 Behnam Khanbeigi <yottanami@gnu.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

export NOTEDITOR_HOME=$(cd "$(dirname "$0")/." >/dev/null 2>&1 ; pwd -P)
LIBRARY_PATH=$(cc -print-file-name=libgccjit.so):$LIBRARY_PATH NOTEDITOR_WM=true ${EMACS_PATH:-emacs} --name Noteditor --no-site-file --no-site-lisp --no-splash --title Noteditor -l $NOTEDITOR_HOME/noteditor-config.el "$@"
