name: Nix

on:
  push:
    branches: [master]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check --all-systems
      - run: nix build .#noteditor
